# Build settings

markdown: kramdown
permalink: pretty

port: 3000

exclude:
  - Gemfile
  - Gemfile.lock
  - package.json
  - node_modules
  - gulpfile.js
  - README.md
  - assets/images
  - assets/scripts
  - assets/styles
  - TODO.md
  - .scss-lint.yml
